Fikser 'Unhandled exception caught for CoroutineName(call-handler)'
java.lang.UnsupportedOperationException: Headers can no longer be set because response was already completed